
PRECISION  = DOUBLE
PROFILE    = FALSE
TINY_PROFILE = TRUE

DEBUG      = FALSE

DIM        = 3

COMP	   = gcc

USE_MPI    = TRUE
USE_OMP    = FALSE
USE_CUDA   = TRUE
USE_PARTICLES = TRUE

Bpack   := ./Make.package
Blocs   := .

include Make.Adv
